[package]
name = "everscale-jrpc-client"
edition = "2021"
version = "0.1.0"

[dependencies]
anyhow = "1"
thiserror = "1.0"
futures = "0.3.23"
log = "0.4.17"
parking_lot = "0.12.0"
rand = "0.8.5"
reqwest = { version = ">=0.11.10", features = ["gzip", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
tokio = { version = "1.20.1", features = ["full"] }

ton_abi = { git = "https://github.com/broxus/ton-labs-abi" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }
ton_block = { git = "https://github.com/broxus/ton-labs-block" }

nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = false }

nekoton-abi = { git = "https://github.com/broxus/nekoton.git" }
everscale-jrpc-models = { path = "../models" }
everscale-proto = { path = "../proto" }
tonic = { version = "0.8.0", default-features = false, features = ["channel"] }
tokio-util = "0.7.3"

[dev-dependencies]
env_logger = "0.9.0"
ed25519-dalek = "1.0.1"
