[package]
name = "everscale-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"

[build-dependencies]
anyhow = "1.0"
prost-build = "0.11"

[features]
default = ["client", "server"]
client = []
server = []

[dev-dependencies]
bincode = "1.3"
borsh = "0.10"
criterion = "0.4.0"

nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = false }
ton_block = { git = "https://github.com/broxus/ton-labs-block.git" }
ton_types = { git = "https://github.com/broxus/ton-labs-types.git" }

[[bench]]
name = "proto"
harness = false

[[bench]]
name = "bincode"
harness = false

[[bench]]
name = "borsh"
harness = false
