[package]
name = "everscale-rpc-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.0", features = ["http2"] }
bytes = "1.4.0"
prost = "0.11"
tracing = "0.1.37"

[build-dependencies]
prost-build = "0.11"
