[package]
name = "everscale-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "3.2"

[build-dependencies]
anyhow = "1.0"
protobuf-codegen = "3.2"

[features]
default = ["client", "server"]
client = []
server = []

[dev-dependencies]
bencher = "0.1.5"
nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = false }
ton_block = { git = "https://github.com/broxus/ton-labs-block.git" }
ton_types = { git = "https://github.com/broxus/ton-labs-types.git" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
borsh = "0.10"

[[bench]]
name = "serialization"
harness = false
